language: dart
dart:
  - stable
install:
  - echo "Configure Flutter"
  - git clone https://github.com/flutter/flutter.git -b beta
  - export PATH="$PATH:`pwd`/flutter/bin"
  - flutter upgrade
  - flutter config --enable-web
  - flutter doctor
script:
  - echo "Building..."
  - flutter build web
deploy:
  if: tag IS present
  provider: firebase
  token: "$FIREBASE_TOKEN"
  skip_cleanup: true