language: dart
dart:
  - stable
install:
  - echo "Configure Flutter"
  - git clone https://github.com/flutter/flutter.git -b beta
  - export PATH="$PATH:`pwd`/flutter/bin"
  - flutter upgrade
  - flutter config --enable-web
  - flutter doctor
script:
  - echo "Building..."
  - flutter pub get
  - flutter clean
  - flutter build web
deploy:
  on:
    tags: true
  provider: firebase
  token: "1//03rR7AS-BtshLCgYIARAAGAMSNwF-L9IrNRXz_ht3C_XE-BkGAgCApBe8_JbO-KZg1CjEVhzYalAWmVt3iJUwQRzbV_zkrvlGi38"
  project: "myfridge-e530e"
  skip_cleanup: true