/// Flutter icons MyFridge
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFridge
///      fonts:
///       - asset: fonts/MyFridge.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFridge {
  MyFridge._();

  static const _kFontFam = 'MyFridge';
  static const String? _kFontPkg = null;

  static const IconData preparation_time_icon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cooking_time_icon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rest_time_icon = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
