name: MyFridge CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
    
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.0'
          channel: stable
      - name: Build web
        run: |
          flutter pub get
          flutter format --set-exit-if-changed .
          flutter analyze
          flutter test
          flutter build web
      - name: Deploy web
        env:
          WEB_DEPLOY_TOKEN: ${{ secrets.WEB_DEPLOY_TOKEN }}
        run: |
          curl -sL https://firebase.tools | bash
          firebase deploy --token $WEB_DEPLOY_TOKEN
